version: '3'

services:
  citsbot:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./config.json:/app/config.json