version: '3'

services:
  citsbot:
    build: ./
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./config.json:/app/config.json
    command: python ./src/main.py